# Base image
FROM node:20

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the workdir
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Set environment variables
#ENV DATABASE_URL postgresql://postgres:postgres@pg_database:5432

# Install Prisma globally
RUN npm i prisma -g
RUN prisma generate

# Build the production version
RUN npm run build

# Copy entrypoint script
COPY .docker/entrypoint.sh entrypoint.sh

# Set the entrypoint for the Docker container
ENTRYPOINT ["/bin/sh", "entrypoint.sh"]
